#include <stdlib.h>
#include <signal.h>
#include "uv.h"

__attribute__ ((visibility ("default")))

int sunglass_UV_E2BIG() { return UV_E2BIG; }
int sunglass_UV_EACCES() { return UV_EACCES; }
int sunglass_UV_EADDRINUSE() { return UV_EADDRINUSE; }
int sunglass_UV_EADDRNOTAVAIL() { return UV_EADDRNOTAVAIL; }
int sunglass_UV_EAFNOSUPPORT() { return UV_EAFNOSUPPORT; }
int sunglass_UV_EAGAIN() { return UV_EAGAIN; }
int sunglass_UV_EAI_ADDRFAMILY() { return UV_EAI_ADDRFAMILY; }
int sunglass_UV_EAI_AGAIN() { return UV_EAI_AGAIN; }
int sunglass_UV_EAI_BADFLAGS() { return UV_EAI_BADFLAGS; }
int sunglass_UV_EAI_BADHINTS() { return UV_EAI_BADHINTS; }
int sunglass_UV_EAI_CANCELED() { return UV_EAI_CANCELED; }
int sunglass_UV_EAI_FAIL() { return UV_EAI_FAIL; }
int sunglass_UV_EAI_FAMILY() { return UV_EAI_FAMILY; }
int sunglass_UV_EAI_MEMORY() { return UV_EAI_MEMORY; }
int sunglass_UV_EAI_NODATA() { return UV_EAI_NODATA; }
int sunglass_UV_EAI_NONAME() { return UV_EAI_NONAME; }
int sunglass_UV_EAI_OVERFLOW() { return UV_EAI_OVERFLOW; }
int sunglass_UV_EAI_PROTOCOL() { return UV_EAI_PROTOCOL; }
int sunglass_UV_EAI_SERVICE() { return UV_EAI_SERVICE; }
int sunglass_UV_EAI_SOCKTYPE() { return UV_EAI_SOCKTYPE; }
int sunglass_UV_EALREADY() { return UV_EALREADY; }
int sunglass_UV_EBADF() { return UV_EBADF; }
int sunglass_UV_EBUSY() { return UV_EBUSY; }
int sunglass_UV_ECANCELED() { return UV_ECANCELED; }
int sunglass_UV_ECHARSET() { return UV_ECHARSET; }
int sunglass_UV_ECONNABORTED() { return UV_ECONNABORTED; }
int sunglass_UV_ECONNREFUSED() { return UV_ECONNREFUSED; }
int sunglass_UV_ECONNRESET() { return UV_ECONNRESET; }
int sunglass_UV_EDESTADDRREQ() { return UV_EDESTADDRREQ; }
int sunglass_UV_EEXIST() { return UV_EEXIST; }
int sunglass_UV_EFAULT() { return UV_EFAULT; }
int sunglass_UV_EFBIG() { return UV_EFBIG; }
int sunglass_UV_EHOSTUNREACH() { return UV_EHOSTUNREACH; }
int sunglass_UV_EINTR() { return UV_EINTR; }
int sunglass_UV_EINVAL() { return UV_EINVAL; }
int sunglass_UV_EIO() { return UV_EIO; }
int sunglass_UV_EISCONN() { return UV_EISCONN; }
int sunglass_UV_EISDIR() { return UV_EISDIR; }
int sunglass_UV_ELOOP() { return UV_ELOOP; }
int sunglass_UV_EMFILE() { return UV_EMFILE; }
int sunglass_UV_EMSGSIZE() { return UV_EMSGSIZE; }
int sunglass_UV_ENAMETOOLONG() { return UV_ENAMETOOLONG; }
int sunglass_UV_ENETDOWN() { return UV_ENETDOWN; }
int sunglass_UV_ENETUNREACH() { return UV_ENETUNREACH; }
int sunglass_UV_ENFILE() { return UV_ENFILE; }
int sunglass_UV_ENOBUFS() { return UV_ENOBUFS; }
int sunglass_UV_ENODEV() { return UV_ENODEV; }
int sunglass_UV_ENOENT() { return UV_ENOENT; }
int sunglass_UV_ENOMEM() { return UV_ENOMEM; }
int sunglass_UV_ENONET() { return UV_ENONET; }
int sunglass_UV_ENOPROTOOPT() { return UV_ENOPROTOOPT; }
int sunglass_UV_ENOSPC() { return UV_ENOSPC; }
int sunglass_UV_ENOSYS() { return UV_ENOSYS; }
int sunglass_UV_ENOTCONN() { return UV_ENOTCONN; }
int sunglass_UV_ENOTDIR() { return UV_ENOTDIR; }
int sunglass_UV_ENOTEMPTY() { return UV_ENOTEMPTY; }
int sunglass_UV_ENOTSOCK() { return UV_ENOTSOCK; }
int sunglass_UV_ENOTSUP() { return UV_ENOTSUP; }
int sunglass_UV_EPERM() { return UV_EPERM; }
int sunglass_UV_EPIPE() { return UV_EPIPE; }
int sunglass_UV_EPROTO() { return UV_EPROTO; }
int sunglass_UV_EPROTONOSUPPORT() { return UV_EPROTONOSUPPORT; }
int sunglass_UV_EPROTOTYPE() { return UV_EPROTOTYPE; }
int sunglass_UV_ERANGE() { return UV_ERANGE; }
int sunglass_UV_EROFS() { return UV_EROFS; }
int sunglass_UV_ESHUTDOWN() { return UV_ESHUTDOWN; }
int sunglass_UV_ESPIPE() { return UV_ESPIPE; }
int sunglass_UV_ESRCH() { return UV_ESRCH; }
int sunglass_UV_ETIMEDOUT() { return UV_ETIMEDOUT; }
int sunglass_UV_ETXTBSY() { return UV_ETXTBSY; }
int sunglass_UV_EXDEV() { return UV_EXDEV; }
int sunglass_UV_UNKNOWN() { return UV_UNKNOWN; }
int sunglass_UV_EOF() { return UV_EOF; }
int sunglass_UV_ENXIO() { return UV_ENXIO; }
int sunglass_UV_EMLINK() { return UV_EMLINK; }